### ISSUE TITLE
remove the hand over face

### ISSUE THREAD

**Issue by andy4120** [willyfh/farl-face-segmentation#2]
hi ,thanks for your job, I wonder can our model can remove the hand part when  hands  over  face  occluded suitation,and the speed  is a little  slow ,how to improve

**Comment by fazilcdev** [comment]
# remove this lines from face_segmentation.py
for i in range(len(seg_labels)):
         for j in range(len(seg_labels[i])):
             seg_labels[i][j] = face_label_mapping[data['seg']['label_names'][seg_labels[i][j]]]
 
# replace with this code (avoid using nested loops and instead use vectorized operations)  
mapping_function = np.vectorize(lambda x: face_label_mapping[data['seg']['label_names'][x]])
seg_labels[:] = torch.from_numpy(mapping_function(seg_labels.cpu().numpy())).to(seg_labels.device)

@andy4120 @willyfh

**Comment by willyfh** [comment]
Hi @andy4120  , sorry for my late response. It would be more appropriate to direct your question or concern to the repository maintainers at https://github.com/FacePerceiver/facer, as I have only utilized the tools provided by them :)

@fazilcdev, thank you for your suggestion. Would you mind opening a pull request to address it? Your contribution would be greatly appreciated!
